# Generated by Django 4.0.6 on 2022-08-13 15:34

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty', '0002_facultydetails_faculty_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facultydetails',
            name='faculty_details',
            field=tinymce.models.HTMLField(),
        ),
    ]
