# Generated by Django 4.0.6 on 2022-08-22 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('imgs', models.FileField(blank=True, default=True, max_length=250, null=True, upload_to='event/')),
            ],
        ),
    ]
