# Generated by Django 4.0.6 on 2022-08-15 05:51

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_title', models.TextField()),
                ('activity_det', tinymce.models.HTMLField()),
                ('activity_img1', models.ImageField(default=True, max_length=250, null=True, upload_to='activity/')),
                ('activity_img2', models.ImageField(default=True, max_length=250, null=True, upload_to='activity/')),
                ('activity_img3', models.ImageField(default=True, max_length=250, null=True, upload_to='activity/')),
            ],
        ),
    ]
