# Generated by Django 4.0.6 on 2022-08-15 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitydetails',
            name='activity_img1',
            field=models.ImageField(blank=True, default=True, max_length=250, null=True, upload_to='activity/'),
        ),
    ]
