# Generated by Django 4.0.6 on 2022-08-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0003_alter_activitydetails_activity_img2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitydetails',
            name='img1_title',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='activitydetails',
            name='img2_title',
            field=models.TextField(default=True),
        ),
        migrations.AddField(
            model_name='activitydetails',
            name='img3_title',
            field=models.TextField(default=True),
        ),
    ]
